# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc9d06c7bd59c7e3c92839d0623a6c60fdb8767638d0f735514b961b13ac029fb029f8ac3224796b66ec9b9f66028056397581de63ef15c12207bcf454a84b4

test:
  secret_key_base: 762d03ce936edea6f2fb4f0d2bd272c41ba4dfdadcdd36e9237ae902212fb6c76f2e0ed08e391e9868b552f0b57d15a51452a5f573761f338cc9cbd7667b7d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
